// src/data/mock-data.js (Updated file)
export const products = [
  {
    id: 1,
    name: "Narwal Freo X Ultra",
    price: 109990.0,
    discountedPrice: 93491.50,
    discountPercentage: 15,
    image: "/images/products/bissel/1558m_main.png",
    category: "Home Cleaning",
    description: "An innovative robotic vacuum and mop with powerful suction, AI DirtSense™ technology, and a self-washing/drying station.",
  },
  {
    id: 2,
    name: "Narwal Freo X Plus",
    price: 25990.0,
    discountedPrice: 20792.00,
    discountPercentage: 20,
    image: "/images/products/bissel/4000m_main.png",
    category: "Home Cleaning",
    description: "A powerful robot vacuum and mop that offers effective mopping capabilities with high downward pressure to tackle stubborn stains.",
  },
  {
    id: 3,
    name: "Bissell SpotClean ProHeat",
    price: 20406.0,
    discountedPrice: 18365.40,
    discountPercentage: 10,
    image: "/images/products/bissel/3700a_main.png",
    category: "Home Cleaning",
    description: "A portable carpet and upholstery cleaner designed to tackle tough spots and stains with heated cleaning technology.",
  },
  {
    id: 4,
    name: "Bissell CrossWave Hydrosteam",
    price: 21990.0,
    discountedPrice: 16492.50,
    discountPercentage: 25,
    image: "/images/products/bissel/3845m_main.png",
    category: "Home Cleaning",
    description: "A multi-surface upright vacuum cleaner that vacuums, mops, and dries simultaneously with the power of HydroSteam technology.",
  },
  {
    id: 5,
    name: "Bissell Featherweight Stick",
    price: 9865.0,
    discountedPrice: 6905.50,
    discountPercentage: 30,
    image: "/images/products/bissel/3912m_main.png",
    category: "Home Cleaning",
    description: "A lightweight, bagless stick vacuum that's perfect for quick clean-ups on both carpets and hard floors.",
  },
  {
    id: 6,
    name: "Narwal Freo Z Ultra",
    price: 94990.0,
    discountedPrice: 80741.50,
    discountPercentage: 15,
    image: "/images/products/bissel/3527m_main.png",
    category: "Home Cleaning",
    description: "A smart cleaning robot with exceptional obstacle avoidance and pet-friendly features, equipped with dual RGB cameras and AI navigation.",
  },
  {
    id: 7,
    name: "Bissell Pet Hair Eraser",
    price: 189.99,
    discountedPrice: 170.99,
    discountPercentage: 10,
    image: "/images/products/bissel/4006m_main.png",
    category: "Home Cleaning",
    description: "A cordless hand vacuum specifically designed to effectively clean up pet hair from a variety of surfaces.",
  },
  {
    id: 8,
    name: "Bissell Little Green",
    price: 4990.0,
    discountedPrice: 3992.00,
    discountPercentage: 20,
    image: "/images/products/bissel/4098m_main.png",
    category: "Home Cleaning",
    description: "A multi-purpose portable carpet and upholstery cleaner, ideal for small messes and spot cleaning.",
  },
  {
    id: 9,
    name: "Bissell PowerClean FurFinder",
    price: 25703.0,
    discountedPrice: 21847.55,
    discountPercentage: 15,
    image: "/images/products/bissel/47203_main.png",
    category: "Home Cleaning",
    description: "A self-standing cordless vacuum with a tangle-free brush roll, designed for homes with pets.",
  },
  {
    id: 10,
    name: "Narwal S20",
    price: 55349.0,
    discountedPrice: 41511.75,
    discountPercentage: 25,
    image: "/images/products/bissel/1558m_main.png",
    category: "Home Cleaning",
    description: "A new all-in-one cordless vacuum and mop cleaner with a zero-tangle brush and AI DirtSense™ technology.",
  },
  {
    id: 11,
    name: "Narwal Flow",
    price: 83000.0, // This is an estimate based on the US price and conversion.
    discountedPrice: 74700.00,
    discountPercentage: 10,
    image: "/images/products/bissel/3527m_main.png",
    category: "Home Cleaning",
    description: "An advanced robot vacuum with a self-cleaning track mop, 22,000Pa suction, and next-gen obstacle avoidance.",
  },
  {
    id: 12,
    name: "Bissell Big Green",
    price: 60296.0,
    discountedPrice: 48236.80,
    discountPercentage: 20,
    image: "/images/products/bissel/3700a_main.png",
    category: "Home Cleaning",
    description: "A professional-grade carpet cleaner with powerful suction and large tanks for deep cleaning large areas.",
  },
  {
    id: 13,
    name: "Bissell ProHeat 2X Revolution",
    price: 49020.0,
    discountedPrice: 36765.00,
    discountPercentage: 25,
    image: "/images/products/bissel/3845m_main.png",
    category: "Home Cleaning",
    description: "A deep carpet cleaner that attacks the toughest stains with Heatwave® Technology and a powerful brush system.",
  },
];

export const featuredProducts = products.slice(0, 6);

export const brands = [
  {
    id: 1,
    name: "Narwal",
    logo: "/narwal.png",
    description: "Live Freely and Passionately - A pioneer in robotic home cleaning solutions.",
    about:
      "Founded in 2016, Narwal is a trailblazer in home cleaning technology, specializing in innovative robotic vacuum and mop solutions. With a focus on cutting-edge AI, self-cleaning systems, and user-centric design, Narwal's mission is to free people from tedious cleaning tasks so they can focus on what truly matters. Their products have won multiple awards and are celebrated for their efficiency and hands-free convenience.",
    founded: "2016",
    headquarters: "Dongguan, China",
    bg: "https://narwalindia.com/wp-content/uploads/2025/07/Untitled-design-19.png",
  },
  {
    id: 2,
    name: "Bissell",
    logo: "/bissel.png",
    description: "The World's Best Floor Care Product Since 1876",
    about:
      "Bissell, also known as Bissell Homecare, is an American privately owned vacuum cleaner and floor care product manufacturing corporation. Founded in 1876 by Melville Bissell, the company has been a leader in the homecare industry for over five generations. They are committed to developing smart, innovative, and practical cleaning solutions, including vacuum cleaners, carpet cleaners, and steam cleaners. Bissell is also deeply committed to animal welfare through the Bissell Pet Foundation.",
    founded: "1876",
    headquarters: "Walker, Michigan, USA",
    bg: "https://www.bissell.in/media/wysiwyg/2.jpg",
  },
];

export const productsWithBrands = products.map((product) => ({
  ...product,
  brandId: product.name.includes("Narwal") ? 1 : 2,
}));


